# Generated by Django 4.2.9 on 2026-10-03 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('regular', '常规授权'), ('emergency', '紧急临时许可')], default='regular', max_length=20, verbose_name='准入类型')),
                ('document_no', models.CharField(blank=True, max_length=100, verbose_name='批准文号')),
                ('valid_from', models.DateField(verbose_name='有效期开始')),
                ('valid_to', models.DateField(verbose_name='有效期截止')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('revoke_reason', models.CharField(blank=True, max_length=200, verbose_name='撤销原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(related_name='authorizations', to='warehouse.category', verbose_name='授权品类范围')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
            ],
            options={
                'verbose_name': '准入授权',
                'verbose_name_plural': '准入授权',
                'db_table': 'wh_authorization',
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name_snapshot', models.CharField(max_length=100, verbose_name='送交时填报单位名称')),
                ('material_name', models.CharField(blank=True, max_length=200, verbose_name='物资名称')),
                ('material_code', models.CharField(blank=True, max_length=50, verbose_name='物资编码')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='数量')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('purpose', models.CharField(choices=[('handover', '新移交'), ('return', '退回')], default='handover', max_length=20, verbose_name='业务类型')),
                ('decision', models.CharField(choices=[('accepted', '接收通过'), ('rejected', '接收拒绝')], max_length=20, verbose_name='接收结论')),
                ('handover_date', models.DateField(verbose_name='接收判定日期')),
                ('basis', models.TextField(verbose_name='判定依据')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='warehouse.authorization', verbose_name='适用准入版本')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='warehouse.category', verbose_name='物资品类')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_handovers', to=settings.AUTH_USER_MODEL, verbose_name='值班员')),
            ],
            options={
                'verbose_name': '移交接收记录',
                'verbose_name_plural': '移交接收记录',
                'db_table': 'wh_handover',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='单位编号')),
                ('name', models.CharField(max_length=100, verbose_name='当前单位名称')),
                ('status', models.CharField(choices=[('active', '合作中'), ('suspended', '已暂停'), ('terminated', '已终止')], default='active', max_length=20, verbose_name='合作状态')),
                ('suspend_reason', models.CharField(blank=True, max_length=200, verbose_name='暂停/终止原因')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfer_units', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '移交单位',
                'verbose_name_plural': '移交单位',
                'db_table': 'wh_transfer_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferUnitNameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='单位名称')),
                ('effective_from', models.DateField(verbose_name='启用日期')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unit_name_records', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_records', to='warehouse.transferunit', verbose_name='移交单位')),
            ],
            options={
                'verbose_name': '移交单位名称记录',
                'verbose_name_plural': '移交单位名称记录',
                'db_table': 'wh_transfer_unit_name',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=100, verbose_name='退回批准单号')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='批准退回数量')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='退回原因')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('used', '已使用'), ('cancelled', '已取消')], default='approved', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='批准时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_approvals', to='warehouse.category', verbose_name='退回品类（空为不限）')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_approvals', to='warehouse.transferunit', verbose_name='移交单位')),
                ('used_handover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_return_approvals', to='warehouse.handover', verbose_name='关联接收记录')),
            ],
            options={
                'verbose_name': '退回批准单',
                'verbose_name_plural': '退回批准单',
                'db_table': 'wh_return_approval',
                'ordering': ['-approved_at'],
                'unique_together': {('unit', 'document_no')},
            },
        ),
        migrations.AddField(
            model_name='handover',
            name='return_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='warehouse.returnapproval', verbose_name='退回批准单'),
        ),
        migrations.AddField(
            model_name='handover',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='warehouse.transferunit', verbose_name='移交单位'),
        ),
        migrations.AddField(
            model_name='handover',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='warehouse.variety', verbose_name='物资品种'),
        ),
        migrations.AddField(
            model_name='authorization',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='warehouse.transferunit', verbose_name='移交单位'),
        ),
    ]
