# Generated by Django 4.2.9 on 2026-10-03 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('all', '全部品类'), ('specified', '指定品类')], default='specified', max_length=20, verbose_name='授权范围')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效日期')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='失效日期')),
                ('version_no', models.CharField(blank=True, max_length=50, verbose_name='授权文号/版本')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(blank=True, related_name='access_grants', to='warehouse.category', verbose_name='授权品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_grants', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '准入授权',
                'verbose_name_plural': '准入授权',
                'db_table': 'wh_access_grant',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='单位名称')),
                ('status', models.CharField(choices=[('active', '正常合作'), ('suspended', '暂停合作')], default='active', max_length=20, verbose_name='合作状态')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='暂停时间')),
                ('suspend_reason', models.CharField(blank=True, max_length=200, verbose_name='暂停原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfer_units', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '移交单位',
                'verbose_name_plural': '移交单位',
                'db_table': 'wh_transfer_unit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitNameChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_name', models.CharField(max_length=100, verbose_name='曾用名')),
                ('current_name', models.CharField(max_length=100, verbose_name='变更后名称')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='生效时间')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_name_changes', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_changes', to='warehouse.transferunit', verbose_name='移交单位')),
            ],
            options={
                'verbose_name': '单位名称变更',
                'verbose_name_plural': '单位名称变更',
                'db_table': 'wh_unit_name_change',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_no', models.CharField(max_length=50, unique=True, verbose_name='批准文号')),
                ('approved_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='批准数量')),
                ('used_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已完成数量')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='有效期开始')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='有效期截止')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_return_approvals', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_approvals', to='warehouse.goods', verbose_name='批准退回货物')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_approvals', to='warehouse.transferunit', verbose_name='退回单位')),
            ],
            options={
                'verbose_name': '退回来件批准',
                'verbose_name_plural': '退回来件批准',
                'db_table': 'wh_return_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='紧急事由')),
                ('scope_type', models.CharField(choices=[('all', '全部品类'), ('specified', '指定品类')], default='specified', max_length=20, verbose_name='许可范围')),
                ('valid_from', models.DateTimeField(verbose_name='有效期开始')),
                ('valid_to', models.DateTimeField(verbose_name='有效期截止')),
                ('approved_by', models.CharField(max_length=50, verbose_name='批准人')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大使用次数')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='是否已撤销')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('categories', models.ManyToManyField(blank=True, related_name='emergency_permits', to='warehouse.category', verbose_name='许可品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergency_permits', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_permits', to='warehouse.transferunit', verbose_name='移交单位')),
            ],
            options={
                'verbose_name': '紧急临时许可',
                'verbose_name_plural': '紧急临时许可',
                'db_table': 'wh_emergency_permit',
                'ordering': ['-valid_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('handover', '新移交'), ('return', '退回')], default='handover', max_length=20, verbose_name='业务类型')),
                ('unit_name_used', models.CharField(blank=True, max_length=100, verbose_name='收件时使用的单位名称')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收件时间')),
                ('decision', models.CharField(choices=[('accepted', '接收通过'), ('rejected', '接收拒绝')], max_length=20, verbose_name='接收结论')),
                ('basis_type', models.CharField(blank=True, choices=[('unit', '单位状态'), ('grant', '常规授权'), ('emergency', '紧急临时许可'), ('return_approval', '已批准退回')], max_length=20, verbose_name='依据类型')),
                ('decision_basis', models.TextField(blank=True, verbose_name='接收判定依据')),
                ('rejection_reason', models.CharField(blank=True, max_length=200, verbose_name='拒绝原因')),
                ('return_approval_no', models.CharField(blank=True, max_length=50, verbose_name='退回来件批准文号')),
                ('batch_no', models.CharField(blank=True, max_length=50, verbose_name='批次号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_transfers', to='warehouse.goods', verbose_name='货物')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse.accessgrant', verbose_name='适用授权版本')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_transfer_ops', to=settings.AUTH_USER_MODEL, verbose_name='值班员')),
                ('permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='warehouse.emergencypermit', verbose_name='适用紧急许可')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='warehouse.transferunit', verbose_name='移交单位')),
            ],
            options={
                'verbose_name': '物资移交记录',
                'verbose_name_plural': '物资移交记录',
                'db_table': 'wh_custody_transfer',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='warehouse.transferunit', verbose_name='移交单位'),
        ),
        migrations.AddConstraint(
            model_name='unitnamechange',
            constraint=models.UniqueConstraint(fields=('unit', 'previous_name'), name='uniq_unit_previous_name'),
        ),
    ]
